name: DeathWorldPlugin
main: io.papermc.deathworld.DeathWorldPlugin
version: 1.3
api-version: 1.12
description: A plugin that manages player worlds upon death and persists the current world across server restarts.
author: Brunight
commands:
  dw:
    description: Main command for DeathWorldPlugin.
    usage: /<command> <subcommand>
    aliases: [deathworld]
    subcommands:
      start:
        description: Starts the world reset process.
        usage: /dw start
      softkill:
        description: Kills a player without counting their death.
        usage: /dw softkill <player>
      lobby:
        description: Teleports the player to the lobby.
        usage: /dw lobby
      setmode:
        description: Set death world mode (default or killall).
        usage: /dw setmode [default|killall]
      setautogeneratenewworld:
        description: Set if a new world will be generated after player death, and if mode is 'world'.
        usage: /dw setautogeneratenewworld [true|false]

permissions:
  dw.command.start:
    description: Allows starting the Death World simulation.
    default: op
  dw.command.softkill:
    description: Softkills a player.
    default: op
  dw.command.lobby:
    description: Allows teleporting to the lobby.
    default: op
  dw.command.setmode:
    description: Allows setting Death World mode.
    default: op
  dw.command.setautogeneratenewworld:
    description: Allows setting if a new world will be generated after player death.
    default: op